import type { TeamQuotaContext, TeamQuotaDimension, TeamRequestDetail } from '@/types/team-requests'
export function contextFixture(dimension: TeamQuotaDimension = 'tokens'): TeamQuotaContext {
  return {
    team_id: 'tea_one',
    dimension,
    currency: dimension === 'tokens' ? null : 'USD',
    platform_currency: 'USD',
    member_stored: '10',
    member_effective: '10',
    team_stored: '100',
    team_effective: '100',
    member_policy_etag: 'a'.repeat(64),
    team_policy_etag: 'b'.repeat(64),
    member_usage: null,
    team_usage: null,
    time_zone: 'UTC',
    month_start: '2026-10-01T00:00:00Z',
    month_end: '2026-11-01T00:00:00Z',
    calendar_etag: 'c'.repeat(64),
    pricing_etag: 'd'.repeat(64),
    resource_created_at: '2026-10-01T00:00:00Z',
    etag: 'e'.repeat(64),
    eligible: true,
    blockers: [],
  }
}
export function requestFixture(dimension: TeamQuotaDimension = 'tokens'): TeamRequestDetail {
  return {
    id: 'tqr_one',
    request_id: '00000000-0000-4000-8000-000000000001',
    team_id: 'tea_one',
    team_name: 'Research Team',
    applicant_user_id: 'usr_member',
    applicant_name: 'Member',
    dimension,
    target_value: '20',
    currency: dimension === 'tokens' ? null : 'USD',
    reason: 'Controlled monthly allowance',
    status: 'pending_team_owner',
    created_at: '2026-10-03T00:00:00Z',
    updated_at: '2026-10-03T00:00:00Z',
    resolved_at: null,
    submitted_snapshot: contextFixture(dimension),
    steps: [
      {
        id: 'qst_owner',
        stage: 'team_owner',
        status: 'pending',
        entered_at: '2026-10-03T00:00:00Z',
        acted_at: null,
        actor_id: null,
        actor_name: null,
        reason: '',
      },
    ],
    current_step_id: 'qst_owner',
    escalation_reason: null,
    approval_preview: {
      member_before: '10',
      member_after: '20',
      team_before: '100',
      team_after: '100',
      escalates: false,
    },
    workspace_available: true,
    current_context: contextFixture(dimension),
    allowed_actions: ['approve', 'reject'],
    etag: 'f'.repeat(64),
    application: null,
  }
}
