// Package handler provides HTTP handlers and route registration.
package handler

import (
	"github.com/fox-gonic/fox"

	"github.com/miclle/routex/internal/routex/service"
	"github.com/miclle/routex/website"
)

// Ctrl is the controller that holds service dependencies and registers routes.
type Ctrl struct {
	service *service.Service
}

// New creates a new Ctrl instance.
func New(svc *service.Service) *Ctrl {
	return &Ctrl{
		service: svc,
	}
}

// RegisterRoutes registers all API routes on the given engine.
func (ctrl *Ctrl) RegisterRoutes(r *fox.Engine) {
	r.RenderErrorFunc = renderAPIError
	// Native query credentials must never be reflected by pre-middleware redirects.
	r.RedirectTrailingSlash = false
	r.RedirectFixedPath = false
	r.Engine.Use(GeminiQueryCredentials, TeamNativeInputs)
	// embed website assets
	website.EmbedAssets(r)

	// ── Health check ────────────────────────────────────────────────────
	r.GET("/health", ctrl.Health)
	r.GET("/v1/models", ctrl.GatewayModels)
	r.POST("/v1/chat/completions", ctrl.GatewayChat)
	r.POST("/v1/responses", ctrl.GatewayResponses)
	r.POST("/v1/messages", ctrl.GatewayMessages)
	r.POST("/v1beta/models/:model_action", ctrl.GatewayGemini)

	// ── API routes ──────────────────────────────────────────────────────
	api := r.Group("/api/v1")
	api.GET("/hello", ctrl.Hello)

	identity := api.Group("")
	identity.Use(authResponseHeaders)
	identity.GET("/setup", ctrl.SetupStatus)
	identity.POST("/setup", sameOrigin, jsonAuthRequest, ctrl.Initialize)
	identity.GET("/site", ctrl.SiteSettings)
	identity.GET("/announcements", ctrl.requireSession, ctrl.ActiveAnnouncements)
	identity.GET("/notifications", ctrl.requireSession, ctrl.Notifications)
	identity.POST("/notifications/:notification_id/read", sameOrigin, ctrl.requireSession, requireCSRF, ctrl.MarkNotificationRead)
	identity.POST("/notifications/read-all", sameOrigin, ctrl.requireSession, requireCSRF, ctrl.MarkAllNotificationsRead)
	identity.GET("/notification-settings", ctrl.requireSession, ctrl.NotificationSettings)
	identity.PUT("/notification-settings", sameOrigin, ctrl.requireSession, requireCSRF, jsonManagementRequest, ctrl.WriteNotificationSettings)
	identity.GET("/auth/registration", ctrl.RegistrationStatus)
	identity.POST("/auth/register", sameOrigin, jsonAuthRequest, ctrl.Register)
	identity.GET("/auth/permissions", ctrl.requireSession, ctrl.CurrentPermissions)
	identity.POST("/auth/login", sameOrigin, jsonAuthRequest, ctrl.Login)
	identity.POST("/auth/mfa/verify", sameOrigin, jsonAuthRequest, ctrl.CompleteMFALogin)
	identity.GET("/auth/session", ctrl.requireSession, ctrl.CurrentSession)
	identity.GET("/overview/accounts", ctrl.requireSession, ctrl.MemberOverviewAccounts)
	identity.POST("/auth/logout", sameOrigin, ctrl.requireSession, requireCSRF, ctrl.Logout)
	identity.GET("/admin/status", ctrl.requireSession, requireAdmin, ctrl.AdminStatus)

	identity.GET("/admin/roles/:role_id", memberMetadataResponseHeaders, ctrl.requireSession, ctrl.GetRoleDefinition)
	identity.PUT("/admin/roles/:role_id", memberMetadataResponseHeaders, ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetReviewedRoleDefinition)

	identity.GET("/teams", ctrl.requireSession, ctrl.ListTeams)
	identity.GET("/teams/:team_id/roles", ctrl.requireSession, ctrl.GetTeamRoles)
	identity.PUT("/teams/:team_id/roles", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetTeamRoles)
	identity.GET("/teams/:team_id/role-candidates", ctrl.requireSession, ctrl.TeamRoleCandidates)
	identity.GET("/teams/:team_id/member-candidates", ctrl.requireSession, ctrl.ScopedTeamMemberCandidates)
	identity.GET("/teams/:team_id/model-candidates", ctrl.requireSession, ctrl.ScopedTeamModelCandidates)
	identity.GET("/teams/:team_id/quota-request-context", ctrl.requireSession, ctrl.TeamQuotaRequestContext)
	identity.POST("/teams/:team_id/quota-requests", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreateTeamQuotaRequest)
	identity.GET("/quota-requests", ctrl.requireSession, ctrl.ListTeamQuotaRequests)
	identity.GET("/quota-requests/:request_id", ctrl.requireSession, ctrl.GetTeamQuotaRequest)
	identity.POST("/quota-requests/:request_id/decision", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.DecideTeamQuotaRequest)
	identity.GET("/admin/quota-requests", ctrl.requireSession, ctrl.ListAdminTeamQuotaRequests)
	identity.GET("/admin/quota-requests/:request_id", ctrl.requireSession, ctrl.GetAdminTeamQuotaRequest)
	identity.GET("/teams/:team_id/limits/default-reset", ctrl.requireSession, ctrl.GetDefaultLimitResetContext)
	identity.POST("/teams/:team_id/limits/default-reset", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.ResetResourceLimitToDefault)
	identity.GET("/teams/:team_id/limits", ctrl.requireSession, ctrl.GetTeamResourceLimit)
	identity.PUT("/teams/:team_id/limits", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetTeamResourceLimit)
	identity.GET("/teams/:team_id/members/:user_id/limits", ctrl.requireSession, ctrl.GetTeamResourceLimit)
	identity.PUT("/teams/:team_id/members/:user_id/limits", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetTeamResourceLimit)
	identity.GET("/teams/:team_id", ctrl.requireSession, ctrl.GetTeam)
	identity.GET("/teams/:team_id/inference-models", ctrl.TeamGatewayModels)
	identity.POST("/teams/:team_id/attachments", ctrl.UploadTeamAttachment)
	identity.GET("/teams/:team_id/attachments/:attachment_id", ctrl.GetTeamAttachment)
	identity.GET("/teams/:team_id/attachments/:attachment_id/content", ctrl.TeamAttachmentContent)
	identity.DELETE("/teams/:team_id/attachments/:attachment_id", ctrl.DeleteTeamAttachment)
	identity.POST("/teams/:team_id/chat/completions", ctrl.TeamGatewayChat)
	identity.POST("/teams/:team_id/models/:model_action", ctrl.TeamGatewayGemini)
	identity.POST("/teams/:team_id/messages", ctrl.TeamGatewayMessages)
	identity.POST("/teams/:team_id/responses", ctrl.TeamGatewayResponses)
	identity.GET("/teams/:team_id/calls", ctrl.requireSession, ctrl.ListTeamCalls)
	identity.GET("/teams/:team_id/calls/export.csv", ctrl.requireSession, ctrl.ExportTeamCalls)
	identity.GET("/teams/:team_id/calls/:request_id", ctrl.requireSession, ctrl.GetTeamCall)
	identity.GET("/projects", ctrl.requireSession, ctrl.ListProjects)
	identity.GET("/projects/creation-manager-candidates", ctrl.requireSession, ctrl.ProjectCreationManagerCandidates)
	identity.GET("/project-creation-resources", ctrl.requireSession, ctrl.GetProjectCreationContext)
	identity.GET("/project-creation-models", ctrl.requireSession, ctrl.ListProjectCreationModels)
	identity.GET("/projects/:project_id/overview", ctrl.requireSession, ctrl.ProjectOverview)
	identity.GET("/projects/:project_id/calls", ctrl.requireSession, ctrl.ListProjectCalls)
	identity.GET("/projects/:project_id/calls/export.csv", ctrl.requireSession, ctrl.ExportProjectCalls)
	identity.GET("/projects/:project_id/calls/:request_id", ctrl.requireSession, ctrl.GetProjectCall)
	identity.GET("/projects/:project_id/manager-candidates", ctrl.requireSession, ctrl.ProjectManagerCandidates)
	identity.GET("/projects/:project_id/limits", ctrl.requireSession, ctrl.GetResourceLimit)
	identity.PUT("/projects/:project_id/limits", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetResourceLimit)
	identity.GET("/projects/:project_id/request-quota-context", ctrl.requireSession, ctrl.ProjectQuotaRequestContext)
	identity.GET("/projects/:project_id/request-limits-context", ctrl.requireSession, ctrl.ProjectRequestLimitsContext)
	identity.GET("/projects/:project_id/requests/:request_id", ctrl.requireSession, ctrl.GetProjectRequest)
	identity.GET("/projects/:project_id/requests", ctrl.requireSession, ctrl.ListProjectRequests)
	identity.GET("/projects/:project_id/request-model-candidates", ctrl.requireSession, ctrl.ProjectRequestCandidates)
	identity.POST("/projects/:project_id/requests", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreateProjectRequest)
	identity.POST("/projects/:project_id/requests/:request_id/decision", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.DecideProjectRequest)
	identity.GET("/projects/:project_id", ctrl.requireSession, ctrl.GetProject)
	identity.POST("/projects", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreateProject)
	identity.PATCH("/projects/:project_id", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.UpdateProject)
	identity.PUT("/projects/:project_id/managers", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetProjectManagers)
	identity.PUT("/projects/:project_id/models", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetProjectModels)
	identity.POST("/projects/:project_id/attachments", ctrl.requireSession, sameOrigin, requireCSRF, ctrl.UploadProjectAttachment)
	identity.GET("/projects/:project_id/attachments/:attachment_id", ctrl.requireSession, ctrl.ProjectAttachment)
	identity.GET("/projects/:project_id/attachments/:attachment_id/content", ctrl.requireSession, ctrl.ProjectAttachmentContent)
	identity.DELETE("/projects/:project_id/attachments/:attachment_id", ctrl.requireSession, sameOrigin, requireCSRF, ctrl.DeleteProjectAttachment)
	projectKeys := identity.Group("/projects/:project_id/keys")
	projectKeys.Use(ctrl.requireSession)
	projectKeys.GET("/:key_id/limits", ctrl.GetResourceLimit)
	projectKeys.PUT("/:key_id/limits", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetResourceLimit)
	projectKeys.GET("", ctrl.ListProjectKeys)
	projectKeys.POST("", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreateProjectKey)
	projectKeys.GET("/:key_id", ctrl.GetProjectKey)
	projectKeys.PATCH("/:key_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.UpdateProjectKey)
	projectKeys.DELETE("/:key_id", sameOrigin, requireCSRF, ctrl.RevokeProjectKey)
	projectKeys.POST("/:key_id/confirm", sameOrigin, requireCSRF, ctrl.ConfirmProjectKey)
	projectKeys.POST("/:key_id/rotate", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RotateProjectKey)
	projectKeys.POST("/:key_id/complete-rotation", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CompleteProjectKeyRotation)
	identity.GET("/usage", ctrl.requireSession, ctrl.PersonalUsage)
	identity.GET("/usage/export.csv", ctrl.requireSession, ctrl.ExportPersonalUsage)
	identity.GET("/teams/:team_id/usage", ctrl.requireSession, ctrl.TeamUsage)
	identity.GET("/teams/:team_id/usage/export.csv", ctrl.requireSession, ctrl.ExportTeamUsage)
	identity.GET("/projects/:project_id/usage", ctrl.requireSession, ctrl.ProjectUsage)
	identity.GET("/projects/:project_id/usage/export.csv", ctrl.requireSession, ctrl.ExportProjectUsage)
	identity.GET("/calls", ctrl.requireSession, ctrl.ListPersonalCalls)
	identity.GET("/calls/export.csv", ctrl.requireSession, ctrl.ExportPersonalCalls)
	identity.GET("/calls/:request_id", ctrl.requireSession, ctrl.GetPersonalCall)
	identity.GET("/account/mfa", ctrl.requireSession, ctrl.AccountMFA)
	identity.POST("/account/mfa/enrollment", sameOrigin, ctrl.requireSession, requireCSRF, jsonAuthRequest, ctrl.BeginMFAEnrollment)
	identity.DELETE("/account/mfa/enrollment", sameOrigin, ctrl.requireSession, requireCSRF, ctrl.CancelMFAEnrollment)
	identity.POST("/account/mfa/enable", sameOrigin, ctrl.requireSession, requireCSRF, jsonAuthRequest, ctrl.EnableMFA)
	identity.POST("/account/mfa/recovery-codes", sameOrigin, ctrl.requireSession, requireCSRF, jsonAuthRequest, ctrl.RegenerateMFARecoveryCodes)
	identity.POST("/account/mfa/disable", sameOrigin, ctrl.requireSession, requireCSRF, jsonAuthRequest, ctrl.DisableMFA)
	identity.GET("/account/sessions", ctrl.requireSession, ctrl.ListAccountSessions)
	identity.PATCH("/account", sameOrigin, ctrl.requireSession, requireCSRF, jsonAuthRequest, ctrl.UpdateProfile)
	identity.POST("/account/password", sameOrigin, ctrl.requireSession, requireCSRF, jsonAuthRequest, ctrl.ChangePassword)
	identity.DELETE("/account/sessions/:session_id", sameOrigin, ctrl.requireSession, requireCSRF, ctrl.RevokeAccountSession)
	identity.GET("/models", ctrl.requireSession, ctrl.ListVisibleModels)
	identity.GET("/model-catalog", ctrl.requireSession, ctrl.ListMemberModelCatalog)
	identity.GET("/model-catalog/:model_id", ctrl.requireSession, ctrl.GetMemberModelCatalog)
	identity.GET("/model-access-candidates", ctrl.requireSession, ctrl.ListModelAccessCandidates)
	identity.GET("/model-access-candidates/:model_id", ctrl.requireSession, ctrl.GetModelAccessCandidate)
	identity.GET("/personal-model-requests", ctrl.requireSession, ctrl.ListPersonalModelRequests)
	identity.GET("/personal-model-requests/:request_id", ctrl.requireSession, ctrl.GetPersonalModelRequest)
	identity.POST("/personal-model-requests", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreatePersonalModelRequest)
	identity.POST("/personal-model-requests/:request_id/decision", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.DecidePersonalModelRequest)
	identity.GET("/team-model-request-teams", ctrl.requireSession, ctrl.ListTeamModelRequestTeams)
	identity.GET("/teams/:team_id/model-request-candidates", ctrl.requireSession, ctrl.ListTeamModelRequestCandidates)
	identity.GET("/teams/:team_id/model-request-candidates/:model_id", ctrl.requireSession, ctrl.GetTeamModelRequestCandidate)
	identity.GET("/team-model-requests", ctrl.requireSession, ctrl.ListOwnTeamModelRequests)
	identity.GET("/team-model-requests/:request_id", ctrl.requireSession, ctrl.GetOwnTeamModelRequest)
	identity.POST("/team-model-requests", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreateTeamModelRequest)
	identity.POST("/team-model-requests/:request_id/decision", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.DecideOwnTeamModelRequest)
	identity.GET("/teams/:team_id/model-request-workspace", ctrl.requireSession, ctrl.TeamModelRequestWorkspace)
	identity.GET("/teams/:team_id/model-requests", ctrl.requireSession, ctrl.ListTeamModelRequests)
	identity.GET("/teams/:team_id/model-requests/:request_id", ctrl.requireSession, ctrl.GetTeamModelRequest)
	identity.POST("/teams/:team_id/model-requests/:request_id/decision", ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.DecideTeamModelRequest)
	identity.POST("/attachments", ctrl.requireSession, sameOrigin, requireCSRF, ctrl.UploadAttachment)
	identity.GET("/attachments/:attachment_id", ctrl.requireSession, ctrl.Attachment)
	identity.GET("/attachments/:attachment_id/content", ctrl.requireSession, ctrl.AttachmentContent)
	identity.DELETE("/attachments/:attachment_id", ctrl.requireSession, sameOrigin, requireCSRF, ctrl.DeleteAttachment)
	identity.GET("/admin/members/:user_id/metadata", memberMetadataResponseHeaders, ctrl.requireSession, ctrl.GetMemberMetadata)
	identity.PUT("/admin/members/:user_id/metadata", memberMetadataResponseHeaders, ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetMemberMetadata)
	identity.GET("/admin/members/:user_id/state", memberMetadataResponseHeaders, ctrl.requireSession, ctrl.GetMemberState)
	identity.PATCH("/admin/members/:user_id", memberMetadataResponseHeaders, ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("members.write"), ctrl.SetReviewedMemberState)
	admin := identity.Group("/admin")
	admin.Use(ctrl.requireSession)
	admin.GET("/members/:user_id/model-access-workspace", ctrl.MemberModelAccessWorkspace)
	admin.GET("/members/:user_id/model-requests", ctrl.ListMemberModelRequests)
	admin.GET("/members/:user_id/model-requests/:request_id", ctrl.GetMemberModelRequest)
	admin.POST("/members/:user_id/model-requests/:request_id/decision", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.DecideMemberModelRequest)
	admin.GET("/team-member-candidates", ctrl.TeamMemberCandidates)
	admin.GET("/resource-model-candidates", ctrl.ResourceModelCandidates)
	admin.GET("/teams", ctrl.RequirePermission("teams.read_all"), ctrl.ListAdminTeams)
	admin.GET("/teams/:team_id", ctrl.GetTeam)
	admin.POST("/teams", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreateTeam)
	admin.PATCH("/teams/:team_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.UpdateTeam)
	admin.PUT("/teams/:team_id/members", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetTeamMembers)
	admin.PUT("/teams/:team_id/models", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetTeamModels)
	admin.GET("/projects", ctrl.RequirePermission("projects.read_all"), ctrl.ListAdminProjects)
	admin.GET("/projects/:project_id", ctrl.GetProject)
	admin.PATCH("/projects/:project_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.UpdateProject)
	admin.PUT("/projects/:project_id/managers", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetProjectManagers)
	admin.PUT("/projects/:project_id/models", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetProjectModels)

	admin.GET("/default-limits/:kind", ctrl.GetDefaultLimit)
	admin.PUT("/default-limits/:kind", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetDefaultLimit)
	admin.GET("/members/:user_id/limits/default-reset", ctrl.GetDefaultLimitResetContext)
	admin.POST("/members/:user_id/limits/default-reset", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.ResetResourceLimitToDefault)
	admin.GET("/members/:user_id/limits", ctrl.GetResourceLimit)
	admin.PUT("/members/:user_id/limits", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetResourceLimit)
	admin.GET("/members/:user_id/offboarding", ctrl.RequirePermission("members.read"), ctrl.OffboardingInventory)
	admin.POST("/members/:user_id/offboarding/plans", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("members.write"), ctrl.CreateOffboardingPlan)
	admin.POST("/members/:user_id/offboarding/:case_id/complete", sameOrigin, requireCSRF, ctrl.RequirePermission("members.write"), ctrl.CompleteOffboarding)
	admin.POST("/members/:user_id/offboarding/emergency", requireAdmin, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.EmergencyOffboarding)
	admin.GET("/members", ctrl.RequirePermission("members.read"), ctrl.ListMembers)
	admin.GET("/members/:user_id", ctrl.RequirePermission("members.read"), ctrl.GetMember)
	admin.GET("/members/:user_id/overview", ctrl.RequirePermission("members.read"), ctrl.MemberOverview)
	admin.GET("/members/:user_id/effective-models", ctrl.RequirePermission("members.read"), ctrl.MemberEffectiveModels)
	admin.GET("/members/:user_id/access", ctrl.RequirePermission("members.read"), ctrl.MemberAccessSummary)
	admin.GET("/members/:user_id/teams", ctrl.RequirePermission("members.read"), ctrl.RequirePermission("teams.read_all"), ctrl.ListMemberTeams)
	admin.GET("/members/:user_id/models", ctrl.GetMemberModels)
	admin.PUT("/members/:user_id/models", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetMemberModels)
	admin.GET("/members/:user_id/keys", ctrl.RequirePermission("members.read"), ctrl.ListMemberKeys)
	admin.GET("/members/:user_id/keys/:key_id", ctrl.RequirePermission("members.read"), ctrl.GetMemberKey)
	admin.POST("/members/:user_id/keys/:key_id/disable", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("members.keys.disable"), ctrl.DisableMemberKey)
	admin.POST("/members", sameOrigin, requireCSRF, jsonAuthRequest, ctrl.RequirePermission("members.write"), ctrl.CreateMember)
	admin.GET("/roles", ctrl.RequirePermission("roles.read"), ctrl.ListRoles)
	admin.POST("/roles", requireAdmin, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreateRole)
	admin.DELETE("/roles/:role_id", requireAdmin, sameOrigin, requireCSRF, ctrl.DeleteRole)
	admin.GET("/members/:user_id/roles", ctrl.RequirePermission("members.read"), ctrl.RequirePermission("roles.read"), ctrl.GetMemberRoles)
	admin.GET("/members/:user_id/roles/candidates", ctrl.RequirePermission("members.read"), ctrl.RequirePermission("roles.read"), ctrl.MemberRoleCandidates)
	admin.GET("/members/:user_id/roles/:role_id", ctrl.RequirePermission("members.read"), ctrl.RequirePermission("roles.read"), ctrl.GetMemberRoleDefinition)
	admin.PUT("/members/:user_id/roles", requireAdmin, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetReviewedMemberRoles)
	identity.GET("/admin/registration", registrationApprovalResponseHeaders, ctrl.requireSession, requireAdmin, ctrl.GetRegistrationPolicy)
	identity.PATCH("/admin/registration", registrationApprovalResponseHeaders, ctrl.requireSession, requireAdmin, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetRegistrationPolicy)
	identity.GET("/admin/members/:user_id/approval", registrationApprovalResponseHeaders, ctrl.requireSession, ctrl.GetMemberApproval)
	identity.PATCH("/admin/members/:user_id/approval", registrationApprovalResponseHeaders, ctrl.requireSession, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetMemberApproval)
	admin.GET("/audit", ctrl.RequirePermission("audit.read"), ctrl.AuditEvents)
	admin.GET("/runtime", ctrl.RequirePermission("system.read"), ctrl.RuntimeStatus)
	admin.GET("/secrets", requireAdmin, ctrl.RequirePermission("secrets.read"), ctrl.GetSecretStore)
	admin.GET("/secrets/rotations/:rotation_id", requireAdmin, ctrl.RequirePermission("secrets.read"), ctrl.GetSecretRotation)
	admin.POST("/secrets/rotations", requireAdmin, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("secrets.rotate"), ctrl.StartSecretRotation)
	admin.POST("/secrets/rotations/:rotation_id/resume", requireAdmin, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("secrets.rotate"), ctrl.ResumeSecretRotation)
	admin.POST("/secrets/rotations/:rotation_id/retire", requireAdmin, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("secrets.rotate"), ctrl.RetireSecretRotation)
	admin.POST("/secrets/rotations/:rotation_id/rollback", requireAdmin, sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("secrets.rotate"), ctrl.RollbackSecretRotation)
	admin.POST("/runtime/publish", requireAdmin, sameOrigin, requireCSRF, ctrl.PublishRuntime)
	admin.GET("/system/instances", ctrl.RequirePermission("system.read"), ctrl.SystemInstances)
	admin.GET("/system/jobs", ctrl.RequirePermission("system.read"), ctrl.SystemJobs)
	admin.GET("/overview", ctrl.RequirePermission("system.read"), ctrl.AdminOverview)
	admin.GET("/alerts", ctrl.RequirePermission("system.read"), ctrl.OperationalAlerts)
	admin.PATCH("/alerts/:alert_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("system.write"), ctrl.UpdateOperationalAlert)
	admin.POST("/system/instances/cleanup", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("system.write"), ctrl.CleanupSystemInstances)
	admin.GET("/quota-settings", ctrl.GetQuotaSettings)
	admin.PUT("/quota-settings", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("limits.settings.write"), ctrl.WriteQuotaSettings)
	admin.GET("/smtp", ctrl.RequirePermission("smtp.read"), ctrl.SMTPSettings)
	admin.PUT("/smtp", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("smtp.write"), ctrl.WriteSMTPSettings)
	admin.PUT("/smtp/sender", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("smtp.write"), ctrl.WriteSMTPSender)
	admin.POST("/smtp/test", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("smtp.test"), ctrl.TestSMTP)
	admin.GET("/storage", ctrl.RequirePermission("storage.read"), ctrl.StorageSettings)
	admin.PUT("/storage", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("storage.write"), ctrl.WriteStorageSettings)
	admin.POST("/storage/test", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("storage.test"), ctrl.TestStorage)
	admin.POST("/storage/rollback", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("storage.write"), ctrl.RollbackStorage)

	admin.GET("/egresses", ctrl.RequirePermission("egress.read"), ctrl.ListEgresses)
	admin.POST("/egresses", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("egress.write"), ctrl.CreateEgress)
	admin.PATCH("/egresses/:egress_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("egress.write"), ctrl.UpdateEgress)
	admin.POST("/egresses/test", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("egress.test"), ctrl.TestEgressDraft)
	admin.POST("/egresses/:egress_id/test", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("egress.test"), ctrl.TestEgress)
	admin.GET("/egress-default", ctrl.RequirePermission("egress.read"), ctrl.EgressDefault)
	admin.PUT("/egress-default", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("egress.write"), ctrl.SetEgressDefault)
	admin.GET("/egress-options", ctrl.RequirePermission("providers.read"), ctrl.EgressOptions)
	admin.PATCH("/connections/:connection_id/egress", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.SetConnectionEgress)
	admin.GET("/prices/repository", ctrl.RequirePermission("prices.read"), ctrl.GetRepositoryPriceSource)
	admin.PUT("/prices/repository", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("prices.write"), ctrl.WriteRepositoryPriceSource)
	admin.GET("/prices/repository/candidates", ctrl.RequirePermission("prices.read"), ctrl.ListRepositoryPriceCandidates)
	admin.POST("/prices/repository/preview", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("prices.read"), ctrl.PreviewRepositoryPrices)
	admin.POST("/prices/repository/apply", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("prices.write"), ctrl.ApplyRepositoryPrices)
	admin.GET("/prices/repository/receipts/:request_id", ctrl.RequirePermission("prices.write"), ctrl.GetRepositoryPriceReceipt)
	admin.GET("/prices", ctrl.RequirePermission("prices.read"), ctrl.ListPrices)
	admin.PATCH("/provider-models/:provider_model_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.SetProviderModelState)
	admin.GET("/provider-models/:provider_model_id/reservation-bound", ctrl.RequirePermission("providers.read"), ctrl.GetReservationBound)
	admin.PUT("/provider-models/:provider_model_id/reservation-bound", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.WriteReservationBound)
	admin.PUT("/site", ctrl.RequirePermission("site.write"), sameOrigin, requireCSRF, jsonManagementRequest, ctrl.UpdateSiteSettings)
	admin.GET("/announcements", ctrl.RequirePermission("system.read"), ctrl.AdminAnnouncements)
	admin.POST("/announcements", ctrl.RequirePermission("announcements.write"), sameOrigin, requireCSRF, jsonManagementRequest, ctrl.PublishAnnouncement)
	admin.PATCH("/announcements/:announcement_id", ctrl.RequirePermission("announcements.write"), sameOrigin, requireCSRF, jsonManagementRequest, ctrl.UpdateAnnouncement)
	admin.POST("/announcements/:announcement_id/close", ctrl.RequirePermission("announcements.write"), sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CloseAnnouncement)
	admin.GET("/usage", ctrl.RequirePermission("calls.read_all"), ctrl.AdminUsage)
	admin.GET("/usage/export.csv", ctrl.RequirePermission("calls.read_all"), ctrl.ExportAdminUsage)
	admin.GET("/provider-models/:provider_model_id/price", ctrl.RequirePermission("prices.read"), ctrl.GetPrice)
	admin.PUT("/prices", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("prices.write"), ctrl.WritePrices)
	admin.PUT("/prices/currency", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("prices.write"), ctrl.WritePricingCurrency)
	admin.GET("/prices/currency", ctrl.RequirePermission("prices.read"), ctrl.GetPricingCurrency)
	admin.POST("/prices/import/preview", sameOrigin, requireCSRF, jsonPriceImportRequest, ctrl.RequirePermission("prices.read"), ctrl.PreviewPriceImport)
	admin.POST("/prices/import/commit", sameOrigin, requireCSRF, jsonPriceImportRequest, ctrl.RequirePermission("prices.write"), ctrl.CommitPriceImport)
	admin.GET("/prices/export.csv", ctrl.RequirePermission("prices.read"), ctrl.ExportPriceCSV)
	admin.POST("/prices/quote", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("prices.read"), ctrl.QuotePrice)

	admin.GET("/calls", ctrl.RequirePermission("calls.read_all"), ctrl.ListAdminCalls)
	admin.GET("/calls/export.csv", ctrl.RequirePermission("calls.read_all"), ctrl.ExportAdminCalls)
	admin.GET("/calls/:request_id", ctrl.RequirePermission("calls.read_all"), ctrl.GetAdminCall)
	admin.GET("/providers", ctrl.RequirePermission("providers.read"), ctrl.ListProviders)
	admin.GET("/providers/:provider_id/quality", ctrl.RequirePermission("providers.read"), ctrl.ProviderQuality)
	admin.GET("/providers/:provider_id/quality-policy", ctrl.RequirePermission("system.read"), ctrl.ProviderQualityPolicy)
	admin.PUT("/providers/:provider_id/quality-policy", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("system.write"), ctrl.WriteProviderQualityPolicy)
	admin.GET("/models", ctrl.RequirePermission("models.read_all"), ctrl.ListAdminModels)
	admin.GET("/models/:model_id", ctrl.RequirePermission("models.read_all"), ctrl.GetAdminModel)
	admin.GET("/model-grantees", ctrl.RequirePermission("models.write"), ctrl.ListModelGrantees)
	admin.POST("/providers", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.CreateProvider)
	admin.POST("/providers/:provider_id/connections", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.CreateConnection)
	admin.POST("/connections/:connection_id/credentials", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.CreateCredential)
	admin.POST("/credentials/:credential_id/verify", sameOrigin, requireCSRF, ctrl.RequirePermission("providers.write"), ctrl.VerifyCredential)
	admin.PATCH("/credentials/:credential_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.UpdateCredential)
	admin.GET("/credentials/:credential_id/metadata", ctrl.RequirePermission("providers.read"), ctrl.GetCredentialMetadata)
	admin.PUT("/credentials/:credential_id/metadata", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.WriteCredentialMetadata)
	admin.DELETE("/credentials/:credential_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.DeleteCredential)
	admin.GET("/credentials/:credential_id/retirement-readiness", ctrl.RequirePermission("providers.read"), ctrl.CredentialRetirementReadiness)
	admin.POST("/credentials/:credential_id/retire", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.RetireCredential)
	admin.POST("/credentials/:credential_id/replacements", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.CreateCredentialReplacement)
	admin.POST("/connections/:connection_id/models", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("providers.write"), ctrl.CreateProviderModel)
	admin.POST("/models", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("models.write"), ctrl.CreateModel)
	admin.POST("/models/:model_id/bindings", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("models.write"), ctrl.AddModelBinding)
	admin.PUT("/models/:model_id/weights", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("models.write"), ctrl.UpdateModelWeights)
	admin.POST("/models/:model_id/rename", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("models.write"), ctrl.RenameModel)
	admin.GET("/model-creation/connections", ctrl.RequirePermission("models.read_all"), ctrl.RequirePermission("providers.read"), ctrl.ListModelCreationConnections)
	admin.GET("/connections/:connection_id/model-creation", ctrl.RequirePermission("models.read_all"), ctrl.RequirePermission("providers.read"), ctrl.GetModelCreationContext)
	admin.GET("/connections/:connection_id/model-creation/provider-models", ctrl.RequirePermission("models.read_all"), ctrl.RequirePermission("providers.read"), ctrl.ListModelCreationProviderModels)
	admin.GET("/connections/:connection_id/model-creation/models", ctrl.RequirePermission("models.read_all"), ctrl.RequirePermission("providers.read"), ctrl.ListModelCreationTargets)
	admin.POST("/connections/:connection_id/model-creation/preview", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("models.read_all"), ctrl.RequirePermission("providers.read"), ctrl.PreviewModelCreationBatch)
	admin.POST("/connections/:connection_id/model-creation", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("models.write"), ctrl.CreateModelBatch)
	admin.GET("/model-creation/receipts/:request_id", ctrl.RequirePermission("models.read_all"), ctrl.RequirePermission("providers.read"), ctrl.GetModelCreationReceipt)
	admin.GET("/models/:model_id/alias-retirement", ctrl.RequirePermission("models.read_all"), ctrl.GetModelAliasRetirement)
	admin.POST("/models/:model_id/alias-retirement", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("models.write"), ctrl.RetireModelAlias)
	admin.PUT("/models/:model_id/grants", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.RequirePermission("models.write"), ctrl.UpdateModelGrants)

	keys := identity.Group("/keys")
	keys.Use(ctrl.requireSession)
	keys.GET("/:key_id/limits", ctrl.GetResourceLimit)
	keys.PUT("/:key_id/limits", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.SetResourceLimit)
	keys.GET("", ctrl.ListPersonalKeys)
	keys.POST("", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CreatePersonalKey)
	keys.POST("/:key_id/confirm", sameOrigin, requireCSRF, ctrl.ConfirmKeyDelivery)
	keys.PATCH("/:key_id", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.UpdatePersonalKey)
	keys.DELETE("/:key_id", sameOrigin, requireCSRF, ctrl.RevokePersonalKey)
	keys.POST("/:key_id/complete-rotation", sameOrigin, requireCSRF, jsonManagementRequest, ctrl.CompletePersonalKeyRotation)
	keys.POST("/:key_id/rotate", sameOrigin, requireCSRF, ctrl.RotatePersonalKey)
}

// Health returns a simple health check response.
func (ctrl *Ctrl) Health(c *fox.Context) string {
	return "ok"
}

// Hello returns a greeting message.
func (ctrl *Ctrl) Hello(c *fox.Context) any {
	return map[string]string{"message": "Hello from RouteX!"}
}
